[rrq]
redis_dsn = "redis://localhost:6379/3"
default_runner_name = "python"

[rrq.runners.python]
type = "socket"
cmd = ["rrq-runner", "--settings", "examples.python.runner_config.python_runner_settings"]
pool_size = 1
max_in_flight = 2

[rrq.runners.rust]
type = "socket"
cmd = ["/opt/rrq-runner"]
pool_size = 1
max_in_flight = 2

[rrq.runner_routes]
rust_queue = "rust"
