[rrq]
redis_dsn = "redis://localhost:6379/3"
default_executor_name = "python"

[rrq.executors.python]
type = "socket"
cmd = ["rrq-executor", "--settings", "examples.python.executor_config.python_executor_settings"]
pool_size = 1
max_in_flight = 2

[rrq.executors.rust]
type = "socket"
cmd = ["/opt/rrq-executor"]
pool_size = 1
max_in_flight = 2

[rrq.executor_routes]
rust_queue = "rust"
