[workspace]
resolver = "2"
members = [
    "runner",
    "orchestrator",
    "producer",
    "protocol",
]

[profile.release]
overflow-checks = true

[workspace.lints.rust]
unsafe_code = "deny"
dead_code = "warn"

[workspace.lints.clippy]
