[package]
name = "rrq-producer-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rrq-producer = { path = "../../../rrq-rs/producer" }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
