[package]
name = "rrq-producer-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rrq-producer = "0.9.9"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
